### ISSUE TITLE
0.3.0 doesn't support macro invocation in default values

### ISSUE THREAD

**Issue by cbiffle** [idanarye/rust-smart-default#4]
I have some code using 0.2.0 that does things like this:

```
#[derive(SmartDefault)]
struct Test {
    #[default = "vec![0; 100]"]
    field: Vec<u32>,
}
```
In 0.3.0 this fails to parse with either syntax:

```
#[derive(SmartDefault)]
struct Test {
    #[default(vec![0; 100])]
    field: Vec<u32>,
    // unexpected token: !
}
#[derive(SmartDefault)]
struct Test2 {
    #[default = vec![0; 100]]
    field: Vec<u32>,
    // expected ']', found '!'
}
```
This is preventing me from upgrading my codebase from 0.2.0 -- which isn't a *huge* deal, since 0.2.0 works fine, but it's adding a dependency on old versions of `syn`/`quote` so I'd like to upgrade.

**Comment by idanarye** [comment]
> which isn't a huge deal

It is actually - 0.2.0 uses an older version of `syn` that does not support Rust 2018, so you can't have Rust 2018 syntax in your struct.

To support macro invocation with the new style, I'll need  [the still unstable `unrestricted_attribute_tokens` feature](https://github.com/rust-lang/rust/pull/57367). Using it with the feature gate doesn't currently work, but it does work if I change the `syn` features to `"full"` - so that's an easy fix. Still - I don't want to have this available only on nightly...

I can add the string version as a special argument. How about this?
```rust
    #[default(_txt = "vec![0; 100]")]
    field: Vec<u32>,
```

**Comment by cbiffle** [comment]
Good point! That syntax would cover my use case. I'd suggest `code` or `_code` for the name to make its purpose more obvious.

**Comment by cbiffle** [comment]
Fantastic! Thank you!

**Comment by idanarye** [comment]
Wait - I just pushed to commit, but I did not upload the version to crates.io yet. I'm waiting for the Travis build to finish.

**Comment by cbiffle** [comment]
Understood -- the "thank you" was for working on it so swiftly. :-)

**Comment by idanarye** [comment]
@cbiffle OK, it's uploaded. Upgrade to 0.4.0 and you are good to go.
